namespace MapleUtils.Parser.Constants
{
    public static class Stats
    {
        public static IReadOnlyDictionary<string, StatEnum> StatMapping = new Dictionary<string, StatEnum>
        {
            ["STR"] = StatEnum.Str,
            ["DEX"] = StatEnum.Dex,
            ["INT"] = StatEnum.Int,
            ["LUK"] = StatEnum.Luk,
            ["힘"] = StatEnum.Str,
            ["민첩"] = StatEnum.Dex,
            ["민첩성"] = StatEnum.Dex,
            ["지력"] = StatEnum.Int,
            ["운"] = StatEnum.Luk,
            ["행운"] = StatEnum.Luk,
            ["MaxHP"] = StatEnum.Hp,
            ["최대 HP"] = StatEnum.Hp,
            ["MaxMP"] = StatEnum.Mp,
            ["최대 MP"] = StatEnum.Mp,
            ["STR%"] = StatEnum.StrP,
            ["DEX%"] = StatEnum.DexP,
            ["INT%"] = StatEnum.IntP,
            ["LUK%"] = StatEnum.LukP,
            ["MaxHP%"] = StatEnum.HpP,
            ["최대 HP%"] = StatEnum.HpP,
            ["MaxMP%"] = StatEnum.MpP,
            ["최대 MP%"] = StatEnum.MpP,
            ["공격력"] = StatEnum.Atk,
            ["마력"] = StatEnum.MAtk,
            ["공격력%"] = StatEnum.AtkP,
            ["마력%"] = StatEnum.MAtkP,
            ["물리방어력"] = StatEnum.Def,
            ["방어력"] = StatEnum.Def,
            ["물리방어력%"] = StatEnum.DefP,
            ["방어력%"] = StatEnum.DefP,
            ["이동속도"] = StatEnum.Speed,
            ["점프력"] = StatEnum.Jump,
            ["몬스터 방어력 무시"] = StatEnum.IgnoreDef,
            ["몬스터 방어력 무시%"] = StatEnum.IgnoreDef,
            ["몬스터 방어율 무시"] = StatEnum.IgnoreDef,
            ["몬스터 방어율 무시%"] = StatEnum.IgnoreDef,
            ["보스 몬스터 공격 시 데미지"] = StatEnum.BossDmg,
            ["보스 몬스터 공격 시 데미지%"] = StatEnum.BossDmg,
            ["데미지"] = StatEnum.Dmg,
            ["데미지%"] = StatEnum.Dmg,
            ["올스탯"] = StatEnum.AllStat,
            ["올스탯%"] = StatEnum.AllStatP,
            ["크리티컬 확률"] = StatEnum.Crit,
            ["크리티컬 확률%"] = StatEnum.Crit,
            ["크리티컬 데미지"] = StatEnum.CritDmg,
            ["크리티컬 데미지%"] = StatEnum.CritDmg,
            ["캐릭터 기준 10레벨 당 STR"] = StatEnum.Lv10Str,
            ["캐릭터 기준 10레벨 당 DEX"] = StatEnum.Lv10Dex,
            ["캐릭터 기준 10레벨 당 INT"] = StatEnum.Lv10Int,
            ["캐릭터 기준 10레벨 당 LUK"] = StatEnum.Lv10Luk,
            ["메소 획득량"] = StatEnum.Meso,
            ["메소 획득량%"] = StatEnum.Meso,
            ["아이템 드롭률"] = StatEnum.Drop,
            ["아이템 드롭률%"] = StatEnum.Drop,
            ["HP 회복 아이템 및 회복 스킬 효율"] = StatEnum.HpHeal,
            ["HP 회복 아이템 및 회복 스킬 효율%"] = StatEnum.HpHeal,
        };
    }
}
